version: "3.8"
   
services:  
  backend:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.3-alpine
    container_name: db-dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - 5432:5432
    volumes: 
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
