# Generated by Django 3.2.15 on 2023-09-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinations_by_manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Location')),
                ('date', models.CharField(max_length=15, verbose_name='Date')),
                ('vaccine', models.CharField(max_length=30, verbose_name='Vaccine')),
                ('total_vaccinations', models.PositiveIntegerField(verbose_name='Total vaccinations')),
            ],
            options={
                'verbose_name': 'Vaccinations_by_manufacturer',
                'verbose_name_plural': 'Vaccinations_by_manufacturers',
            },
        ),
    ]
